language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t heplayskeys/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true heplayskeys/docker-react npm run test
## If deploying service/app to AWS Elastic Beanstalk
# deploy:
#   provider: elasticbeanstalk
#   region: "us-west-2"
#   app: "docker"
#   env: "Docker-env"
#   bucket_name: {elasticbeanstalk-us-west-2-{S3 BUCKET HASH}}
#   bucket_path: "docker"
#   on:
#     branch: master
